[settings]
dotfiles.root = "~/.dotfiles"
experimental = true

[dotfiles]
# Repository and Mise configuration
"~/.dotfiles" = "~/src/github.com/jclem/dotfiles2"
"~/.config/mise/config.toml" = "~/src/github.com/jclem/dotfiles2/mise.toml"

# Fish shell configuration
"~/.config/fish/config.fish" = ".config/fish/config.fish"
"~/.config/fish/conf.d/" = ".config/fish/conf.d/"
