[tools]
actionlint = "latest"
age = "1.3.1"
amp = "0.0.1771848350-g31e659"
bun = "latest"
elixir = "latest"
erlang = "latest"
flyctl = "0.4.14"
fnox = "1.12.1"
gcloud = "557.0.0"
"github:jclem/konk" = "latest"
glow = "2.1.1"
go = "latest"
graphite = "1.7.20"
just = "1.46.0"
lazygit = "latest"
neovim = "0.11.6"
node = "25.8.1"
npm = "latest"
op = "2.32.1"
oxker = "latest"
pnpm = "latest"
rebar = "latest"
ruby = "4.0.1"
rust = "1.93.1"
terraform = "1.14.5"
usage = "2.18.0"
uv = "0.10.4"
zig = "0.15.2"

[settings]
experimental = true
