set -g prefix C-g

bind-key | split-window -h
bind-key - split-window -v

bind-key C-h select-pane -L
bind-key C-j select-pane -D
bind-key C-k select-pane -U
bind-key C-l select-pane -R

bind-key L send-keys -R C-l \; clear-history

bind-key P switch-client -l

set -g mouse on

set -g @rose_pine_variant "moon"
set -g @rose_pine_host "off"
set -g @rose_pine_user "off"
set -g @rose_pine_session_icon "s"
set -g @rose_pine_current_window_icon "w"
set -g @rose_pine_folder_icon "f"
set -g @rose_pine_username_icon "u"
set -g @rose_pine_hostname_icon "h"
set -g @rose_pine_date_time_icon "t"
set -g @rose_pine_window_status_separator " "

set -g @resurrect-dir "$XDG_STATE_HOME/tmux/resurrect"

set -g @plugin "rose-pine/tmux"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tpm"

run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
