set -g prefix C-g

# Window splitting
bind-key | split-window -h
bind-key - split-window -v

# Pane navigation
bind-key -r C-h select-pane -L
bind-key -r C-j select-pane -D
bind-key -r C-k select-pane -U
bind-key -r C-l select-pane -R

# Pane resizing
bind-key -r H resize-pane -L 5
bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r L resize-pane -R 5

# Choose session/window tree
bind-key -r s choose-tree -s -Oname

# Reload configuration
bind-key R source-file "$XDG_CONFIG_HOME/tmux/tmux.conf"

# Edit configuration
bind-key M split-window -h "nvim $CODE/jclem/dotfiles/dot_config/tmux/tmux.conf"

bind-key L send-keys -R C-l \; clear-history

bind-key P switch-client -l

set -g mouse on

set -g @rose_pine_variant "dawn"
set -g @rose_pine_host "off"
set -g @rose_pine_user "off"
set -g @rose_pine_show_current_program "on"
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_current_window_icon '' # Changes the default icon to the left of the active window name
set -g @rose_pine_folder_icon '' # Changes the default icon to the left of the current directory folder
set -g @rose_pine_username_icon '' # Changes the default icon to the right of the hostname
set -g @rose_pine_hostname_icon '󰒋' # Changes the default icon to the right of the hostname
set -g @rose_pine_date_time_icon '󰃰' # Changes the default icon to the right of the date module
set -g @rose_pine_window_status_separator "  " # Changes the default icon that appears between window names

set -g @resurrect-dir "$XDG_STATE_HOME/tmux/resurrect"

set -g @logging-path "$XDG_DATA_HOME/tmux/logging"
set -g @logging_key "C-g"
set -g @logging-filename "#{session_name}-#{window_index}-#{pane_index}-%Y-%m-%dT%H-%M-%S.log"

# Open logging-path in Finder
bind-key G run-shell "open $XDG_DATA_HOME/tmux/logging"

set -g history-limit 500000

set -g @plugin "rose-pine/tmux"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-logging"
set -g @plugin "alexwforsythe/tmux-which-key"

run "$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm"
